/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoedd_2;

import javax.swing.*;
import java.io.*;
import java.awt.event.ActionEvent;
import org.json.simple.*;
import org.json.simple.parser.*;

/**
 * Clase Ventana1 para crear una interfaz gráfica de usuario en la que se pueda cargar archivos JSON desde el dispositivo y leer el mismo.
 * 
 * @author Sofia Machado
 */
public class Ventana1 extends javax.swing.JFrame {

    /**
     * Constructor de la clase Ventana1.
     * Este constructor lo que hace es inicializar los componentes de la ventana y a la vez centra la ventana en la pantalla.
     */
    public Ventana1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CargarJSON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Carga y lectura de JSON");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        CargarJSON.setText("Cargar");
        CargarJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarJSONActionPerformed(evt);
            }
        });
        jPanel1.add(CargarJSON, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    /**
     * Este boton le permite al usuario seleccionar un archivo JSON de sus archivos y procesa su contenido.
     */
    private void CargarJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarJSONActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos JSON", "json"));
        int returnValue = fileChooser.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            StringBuilder jsonContent = new StringBuilder();
            try (BufferedReader reader = new BufferedReader(new FileReader(selectedFile))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    jsonContent.append(line);
                }
            } catch (IOException e) {
                e.printStackTrace();
            }

            String jsonString = jsonContent.toString();

            /**
            * Como se encontró un doble espacio en uno de los JSON proporcionados que estaba causando problemas con su lectura
            * se implementó una manera de reemplazar múltiples espacios por un solo espacio y evitar errores
            */
            jsonString = jsonString.trim().replaceAll(" +", " ");

            // Verifica si el JSON está vacío  
            if (jsonString.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "El JSON seleccionado está vacío.");
                return;
            }

            // Mapa para registrar los nombres ya encontrados  
            String[] names = new String[100];  
            int nameCount = 0;

            // Procesa el JSON  
            try {
                JSONParser parser = new JSONParser();
                JSONObject jsonObject = (JSONObject) parser.parse(jsonString);
                for (Object houseName : jsonObject.keySet()) {
                    JSONArray houseArray = (JSONArray) jsonObject.get(houseName);
                    for (Object person : houseArray) {
                        JSONObject personObject = (JSONObject) person;
                        String personName = (String) personObject.keySet().iterator().next();
                        JSONArray personDetails = (JSONArray) personObject.get(personName);
                        String ofHisName = null;

                        for (Object detail : personDetails) {
                            JSONObject detailObject = (JSONObject) detail;
                            if (detailObject.containsKey("Of his name")) {
                                ofHisName = (String) detailObject.get("Of his name");
                            }
                        }

                        boolean isRepeated = false;

                        // Comprobar si el nombre ya había sido leído, es decir, es un nombre repetido  
                        for (int i = 0; i < nameCount; i++) {
                            if (names[i].equals(personName)) {
                                isRepeated = true;
                                break;
                            }
                        }

                        // Si es un nombre repetido, se modifica el nombre para que se muestre con su posición en la familia  
                        if (isRepeated && ofHisName != null) {
                            personName += " the " + ofHisName;
                        } else {
                            // Si es un nombre no repetido, se añade a la lista  
                            names[nameCount++] = personName;
                        }

                        // Se Crea un diccionario para almacenar los detalles de la persona  
                        StringBuilder detailsOutput = new StringBuilder(personName + " : { ");

                        for (Object detail : personDetails) {
                            JSONObject detailObject = (JSONObject) detail;
                            String detailKey = (String) detailObject.keySet().iterator().next();
                            Object detailValue = detailObject.get(detailKey);

                            if (detailValue instanceof JSONArray) {
                                detailsOutput.append(detailKey).append(" : ").append(detailValue.toString()).append(", ");
                            } else {
                                detailsOutput.append(detailKey).append(" : ")
                                        .append(detailValue != null ? detailValue.toString() : null).append(", ");
                            }
                        }

                        // Muestra por consola  
                        detailsOutput = new StringBuilder(detailsOutput.substring(0, detailsOutput.length() - 2) + " }");
                        System.out.println(detailsOutput);
                    }
                }
            } catch (ParseException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error al parsear el JSON.");
            }
        }
    }//GEN-LAST:event_CargarJSONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarJSON;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
