/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import proyectoedd_2.Persona;
import static Interfaces.Json.arbolGenealogico;
import static Interfaces.Json.validar;
import javax.swing.JOptionPane;

/**
 * Clase que representa la interfaz gráfica para buscar una persona por su título.
 * Extiende de JFrame para crear una ventana de aplicación.
 * 
 * @author Andrea Villasmil
 */
public class BuscarTitulo extends javax.swing.JFrame {
    private Persona[] coincidencias;
    /**
     * Creates new form BuscarTitulo
     */
    public BuscarTitulo() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tituloTF = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        personaTF = new javax.swing.JTextArea();
        botonRegresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        NumeroPersona = new javax.swing.JTextField();
        detallesPersona = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar Persona por Título");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese el número correspondiente a la persona:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        tituloTF.setForeground(new java.awt.Color(153, 153, 153));
        tituloTF.setText("título...");
        getContentPane().add(tituloTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 307, -1));

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        personaTF.setColumns(20);
        personaTF.setRows(5);
        jScrollPane1.setViewportView(personaTF);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 102, 385, 160));

        botonRegresar.setText("<Regresar al Menú");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Escriba el título de la persona que busca: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        getContentPane().add(NumeroPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 80, -1));

        detallesPersona.setText("Ver detalles de persona");
        detallesPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detallesPersonaActionPerformed(evt);
            }
        });
        getContentPane().add(detallesPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/arbolbg.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        Menu menu = new Menu();
        this.dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // Obtener el título ingresado por el usuario en el campo de texto
        String titulo = tituloTF.getText();
    
        // Llamar al método buscarTitulo del árbol genealógico y guardar el resultado
        coincidencias = arbolGenealogico.buscarConTitulo(titulo);
    
        // Verificar si se encontraron resultados
        if (coincidencias != null) {
        // Si hay resultados, mostrar los resultados en el área de texto
        String resultados = arbolGenealogico.mostrarHallazgos(coincidencias);
        personaTF.setText(resultados);
        } else {
        // Si no hay resultados, mostrar un mensaje de advertencia
        JOptionPane.showMessageDialog(null, "No se encontraron coincidencias con la búsqueda");
    }
    
        // Limpiar el campo de texto de búsqueda
        tituloTF.setText("");
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void detallesPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detallesPersonaActionPerformed
        String indiceStr = NumeroPersona.getText();
        if (validar.validarNumeros(indiceStr) != -1) {
            int index = validar.validarNumeros(indiceStr);
            if (validar.validarIndice(coincidencias.length, index)) {
                JOptionPane.showMessageDialog(null, coincidencias[index].toString());
            } else {
                JOptionPane.showMessageDialog(null, "Indice Invalido");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe ser un numero entero");
        }
        NumeroPersona.setText("");
    }//GEN-LAST:event_detallesPersonaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarTitulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NumeroPersona;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton detallesPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea personaTF;
    private javax.swing.JTextField tituloTF;
    // End of variables declaration//GEN-END:variables
}
