/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import static Interfaces.Json.arbolGenealogico;
import javax.swing.DefaultComboBoxModel;
import proyectoedd_2.Persona;

/**
 * Clase Generación que extiende JFrame para mostrar los integrantes de una generación específica.
 * Permite al usuario seleccionar una generación y ver sus integrantes.
 * 
 * @author Andrea Villasil
 */
public class Generación extends javax.swing.JFrame {
    DefaultComboBoxModel opcionesDeGeneracion = new DefaultComboBoxModel(); // Modelo para el combo box de generaciones
    private Persona[] resultados = null; // Almacena los resultados de la búsqueda de generación
    
    /**
     * Constructor de la clase Generación.
     * Inicializa los componentes de la interfaz y configura la ventana.
     */
    
    public Generación() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.formarGeneracion(); // Llena el combo box con las generaciones existentes
    }
    
    /**
     * Llena el combo box con las generaciones existentes en el árbol genealógico.
     */
    
    private void formarGeneracion(){
        for (int i = 0; i < arbolGenealogico.generacionesExistentes().getCantidad(); i++) {
            opcionesDeGeneracion.addElement(arbolGenealogico.generacionesExistentes().getValor(i));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        coincidenciasTF = new javax.swing.JTextArea();
        botonRegresar = new javax.swing.JButton();
        boxGeneraciones = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Integrantes de una misma Generación");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Escribe el número de la generación de la cual desee ver sus integrantes: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 41, -1, -1));

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        coincidenciasTF.setColumns(20);
        coincidenciasTF.setRows(5);
        jScrollPane1.setViewportView(coincidenciasTF);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 98, 494, 156));

        botonRegresar.setText("< Regresar al Menú");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 266, -1, -1));

        boxGeneraciones.setModel(opcionesDeGeneracion);
        boxGeneraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxGeneracionesActionPerformed(evt);
            }
        });
        jPanel1.add(boxGeneraciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 400, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/arbolbg.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método llamado al presionar el botón "Regresar al Menú".
     * Cierra la ventana actual y abre el menú principal.
     */
    
    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        Menu menu = new Menu();
        this.dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

     /**
     * Método llamado al presionar el botón "Buscar".
     * Busca los integrantes de la generación seleccionada y los muestra en el área de texto.
     */
    
    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        int numGen = (int) boxGeneraciones.getSelectedItem();
        resultados = arbolGenealogico.buscarGeneracion(numGen);
        if(resultados==null){
            coincidenciasTF.setText("No hay resultados que coincidan con tu busqueda\n");
        }else{
            coincidenciasTF.setText(arbolGenealogico.mostrarGeneracion(resultados, numGen));   
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void boxGeneracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxGeneracionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxGeneracionesActionPerformed

    /**
     * Método principal para ejecutar la aplicación.
     * Configura el look and feel y muestra la ventana de generación.
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Generación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Generación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Generación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Generación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Generación().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JComboBox<String> boxGeneraciones;
    private javax.swing.JTextArea coincidenciasTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
